<template>
    <!-- Add here any string that are not present elsewhere, but are dynamiclly generated by IU-->
    <span>
        <span v-translate>Create a new route</span>
        <!-- TODO 10 types  -->

        <span v-translate>routes</span>
        <!-- TODO 10 types, plural -->
    </span>
</template>
