<template>
  <!-- Add here any string that are not present elsewhere, but are dynamically generated by UI-->
  <!-- TODO : remove this file, and place in comments fixed string : it's not possible to follow
    where this string are used otherwise -->
  <span>
    <span v-translate>articles</span>
    <span v-translate>areas</span>
    <span v-translate>books</span>
    <span v-translate>images</span>
    <span v-translate>maps</span>
    <span v-translate>outings</span>
    <span v-translate>routes</span>
    <span v-translate>xreports</span>
    <span v-translate>waypoints</span>
    <span v-translate>profiles</span>

    <span v-translate>article</span>
    <span v-translate>area</span>
    <span v-translate>book</span>
    <span v-translate>image</span>
    <span v-translate>map</span>
    <span v-translate>outing</span>
    <span v-translate>route</span>
    <span v-translate>xreport</span>
    <span v-translate>waypoint</span>
    <span v-translate>profile</span>
  </span>
</template>
