<template>
  <!-- auto-generated by tools/update-c2c-common.py -->
  <span>
    <span v-translate>access</span>
    <span v-translate>access_comment</span>
    <span v-translate>access_condition</span>
    <span v-translate>access_period</span>
    <span v-translate>access_time</span>
    <span v-translate>activities</span>
    <span v-translate>activity_rate</span>
    <span v-translate>age</span>
    <span v-translate>aid_rating</span>
    <span v-translate>anonymous</span>
    <span v-translate>area_type</span>
    <span v-translate>areas</span>
    <span v-translate>article_categories</span>
    <span v-translate>article_type</span>
    <span v-translate>articles</span>
    <span v-translate>author</span>
    <span v-translate>author_status</span>
    <span v-translate>autonomy</span>
    <span v-translate>avalanche_level</span>
    <span v-translate>avalanche_signs</span>
    <span v-translate>avalanche_slope</span>
    <span v-translate>avalanches</span>
    <span v-translate>best_periods</span>
    <span v-translate>blanket_unstaffed</span>
    <span v-translate>book_types</span>
    <span v-translate>books</span>
    <span v-translate>camera_name</span>
    <span v-translate>capacity</span>
    <span v-translate>capacity_staffed</span>
    <span v-translate>categories</span>
    <span v-translate>children_proof</span>
    <span v-translate>climbing_indoor_types</span>
    <span v-translate>climbing_outdoor_type</span>
    <span v-translate>climbing_outdoor_types</span>
    <span v-translate>climbing_rating_max</span>
    <span v-translate>climbing_rating_median</span>
    <span v-translate>climbing_rating_min</span>
    <span v-translate>climbing_styles</span>
    <span v-translate>code</span>
    <span v-translate>condition_rating</span>
    <span v-translate>conditions</span>
    <span v-translate>conditions_levels</span>
    <span v-translate>configuration</span>
    <span v-translate>custodianship</span>
    <span v-translate>date</span>
    <span v-translate>date_end</span>
    <span v-translate>date_start</span>
    <span v-translate>date_time</span>
    <span v-translate>description</span>
    <span v-translate>difficulties_height</span>
    <span v-translate>disable_comments</span>
    <span v-translate>durations</span>
    <span v-translate>editor</span>
    <span v-translate>elevation</span>
    <span v-translate>elevation_access</span>
    <span v-translate>elevation_down_snow</span>
    <span v-translate>elevation_max</span>
    <span v-translate>elevation_min</span>
    <span v-translate>elevation_up_snow</span>
    <span v-translate>engagement_rating</span>
    <span v-translate>equipment_rating</span>
    <span v-translate>equipment_ratings</span>
    <span v-translate>event_activity</span>
    <span v-translate>event_type</span>
    <span v-translate>exposition_rock_rating</span>
    <span v-translate>exposure_time</span>
    <span v-translate>external_resources</span>
    <span v-translate>file_size</span>
    <span v-translate>filename</span>
    <span v-translate>fnumber</span>
    <span v-translate>focal_length</span>
    <span v-translate>frequentation</span>
    <span v-translate>gas_unstaffed</span>
    <span v-translate>gear</span>
    <span v-translate>gender</span>
    <span v-translate>glacier_gear</span>
    <span v-translate>glacier_rating</span>
    <span v-translate>global_rating</span>
    <span v-translate>ground_types</span>
    <span v-translate>group_management</span>
    <span v-translate>heating_unstaffed</span>
    <span v-translate>height</span>
    <span v-translate>height_diff_access</span>
    <span v-translate>height_diff_difficulties</span>
    <span v-translate>height_diff_down</span>
    <span v-translate>height_diff_up</span>
    <span v-translate>height_max</span>
    <span v-translate>height_median</span>
    <span v-translate>height_min</span>
    <span v-translate>hiking_mtb_exposition</span>
    <span v-translate>hiking_rating</span>
    <span v-translate>hut_comment</span>
    <span v-translate>hut_status</span>
    <span v-translate>ice_rating</span>
    <span v-translate>image_categories</span>
    <span v-translate>image_type</span>
    <span v-translate>images</span>
    <span v-translate>increase_impact</span>
    <span v-translate>isbn</span>
    <span v-translate>iso_speed</span>
    <span v-translate>labande_global_rating</span>
    <span v-translate>labande_ski_rating</span>
    <span v-translate>lang</span>
    <span v-translate>langs</span>
    <span v-translate>length</span>
    <span v-translate>length_total</span>
    <span v-translate>lift_access</span>
    <span v-translate>lift_status</span>
    <span v-translate>main_waypoint_id</span>
    <span v-translate>maps_info</span>
    <span v-translate>matress_unstaffed</span>
    <span v-translate>mixed_rating</span>
    <span v-translate>modifications</span>
    <span v-translate>motivations</span>
    <span v-translate>mtb_down_rating</span>
    <span v-translate>mtb_height_diff_portages</span>
    <span v-translate>mtb_length_asphalt</span>
    <span v-translate>mtb_length_trail</span>
    <span v-translate>mtb_up_rating</span>
    <span v-translate>name</span>
    <span v-translate>nb_impacted</span>
    <span v-translate>nb_pages</span>
    <span v-translate>nb_participants</span>
    <span v-translate>orientations</span>
    <span v-translate>other_comments</span>
    <span v-translate>outings</span>
    <span v-translate>paragliding_rating</span>
    <span v-translate>parking_fee</span>
    <span v-translate>partial_trip</span>
    <span v-translate>participant_count</span>
    <span v-translate>participants</span>
    <span v-translate>phone</span>
    <span v-translate>phone_custodian</span>
    <span v-translate>place</span>
    <span v-translate>previous_injuries</span>
    <span v-translate>product_types</span>
    <span v-translate>prominence</span>
    <span v-translate>protected</span>
    <span v-translate>public_transport</span>
    <span v-translate>public_transportation_rating</span>
    <span v-translate>public_transportation_types</span>
    <span v-translate>publication_date</span>
    <span v-translate>qualification</span>
    <span v-translate>quality</span>
    <span v-translate>rain_proof</span>
    <span v-translate>reduce_impact</span>
    <span v-translate>remarks</span>
    <span v-translate>rescue</span>
    <span v-translate>risk</span>
    <span v-translate>risk_rating</span>
    <span v-translate>rock_free_rating</span>
    <span v-translate>rock_required_rating</span>
    <span v-translate>rock_types</span>
    <span v-translate>route_description</span>
    <span v-translate>route_history</span>
    <span v-translate>route_length</span>
    <span v-translate>route_study</span>
    <span v-translate>route_types</span>
    <span v-translate>routes</span>
    <span v-translate>routes_quantity</span>
    <span v-translate>safety</span>
    <span v-translate>scale</span>
    <span v-translate>severity</span>
    <span v-translate>ski_exposition</span>
    <span v-translate>ski_rating</span>
    <span v-translate>slackline_anchor1</span>
    <span v-translate>slackline_anchor2</span>
    <span v-translate>slackline_height</span>
    <span v-translate>slackline_length_max</span>
    <span v-translate>slackline_length_min</span>
    <span v-translate>slackline_type</span>
    <span v-translate>slackline_types</span>
    <span v-translate>slope</span>
    <span v-translate>snow_clearance_rating</span>
    <span v-translate>snow_quality</span>
    <span v-translate>snow_quantity</span>
    <span v-translate>snowshoe_rating</span>
    <span v-translate>summary</span>
    <span v-translate>supervision</span>
    <span v-translate>time_management</span>
    <span v-translate>timing</span>
    <span v-translate>title</span>
    <span v-translate>training</span>
    <span v-translate>url</span>
    <span v-translate>users</span>
    <span v-translate>via_ferrata_rating</span>
    <span v-translate>waypoint_slope</span>
    <span v-translate>waypoint_type</span>
    <span v-translate>waypoints</span>
    <span v-translate>weather</span>
    <span v-translate>weather_station_types</span>
    <span v-translate>width</span>
    <span v-translate>xreports</span>
    <!-- access_conditions -->
    <span v-translate translate-context="access_conditions">cleared</span>
    <span v-translate translate-context="access_conditions">snowy</span>
    <span v-translate translate-context="access_conditions">closed_snow</span>
    <span v-translate translate-context="access_conditions">closed_cleared</span>
    <!-- access_times -->
    <span v-translate translate-context="access_times">1min</span>
    <span v-translate translate-context="access_times">5min</span>
    <span v-translate translate-context="access_times">10min</span>
    <span v-translate translate-context="access_times">15min</span>
    <span v-translate translate-context="access_times">20min</span>
    <span v-translate translate-context="access_times">30min</span>
    <span v-translate translate-context="access_times">45min</span>
    <span v-translate translate-context="access_times">1h</span>
    <span v-translate translate-context="access_times">1h30</span>
    <span v-translate translate-context="access_times">2h</span>
    <span v-translate translate-context="access_times">2h30</span>
    <span v-translate translate-context="access_times">3h</span>
    <span v-translate translate-context="access_times">3h+</span>
    <!-- activities -->
    <span v-translate translate-context="activities">skitouring</span>
    <span v-translate translate-context="activities">snow_ice_mixed</span>
    <span v-translate translate-context="activities">mountain_climbing</span>
    <span v-translate translate-context="activities">rock_climbing</span>
    <span v-translate translate-context="activities">ice_climbing</span>
    <span v-translate translate-context="activities">hiking</span>
    <span v-translate translate-context="activities">snowshoeing</span>
    <span v-translate translate-context="activities">paragliding</span>
    <span v-translate translate-context="activities">mountain_biking</span>
    <span v-translate translate-context="activities">via_ferrata</span>
    <span v-translate translate-context="activities">slacklining</span>
    <!-- activity_rates -->
    <span v-translate translate-context="activity_rates">activity_rate_y5</span>
    <span v-translate translate-context="activity_rates">activity_rate_m2</span>
    <span v-translate translate-context="activity_rates">activity_rate_w1</span>
    <!-- area_types -->
    <span v-translate translate-context="area_types">range</span>
    <span v-translate translate-context="area_types">admin_limits</span>
    <span v-translate translate-context="area_types">country</span>
    <!-- article_categories -->
    <span v-translate translate-context="article_categories">mountain_environment</span>
    <span v-translate translate-context="article_categories">gear</span>
    <span v-translate translate-context="article_categories">technical</span>
    <span v-translate translate-context="article_categories">topoguide_supplements</span>
    <span v-translate translate-context="article_categories">soft_mobility</span>
    <span v-translate translate-context="article_categories">expeditions</span>
    <span v-translate translate-context="article_categories">stories</span>
    <span v-translate translate-context="article_categories">c2c_meetings</span>
    <span v-translate translate-context="article_categories">tags</span>
    <span v-translate translate-context="article_categories">site_info</span>
    <span v-translate translate-context="article_categories">association</span>
    <!-- article_types -->
    <span v-translate translate-context="article_types">collab</span>
    <span v-translate translate-context="article_types">personal</span>
    <!-- author_statuses -->
    <span v-translate translate-context="author_statuses">primary_impacted</span>
    <span v-translate translate-context="author_statuses">secondary_impacted</span>
    <span v-translate translate-context="author_statuses">internal_witness</span>
    <span v-translate translate-context="author_statuses">external_witness</span>
    <!-- autonomies -->
    <span v-translate translate-context="autonomies">non_autonomous</span>
    <span v-translate translate-context="autonomies">autonomous</span>
    <span v-translate translate-context="autonomies">expert</span>
    <!-- avalanche_levels -->
    <span v-translate translate-context="avalanche_levels">level_1</span>
    <span v-translate translate-context="avalanche_levels">level_2</span>
    <span v-translate translate-context="avalanche_levels">level_3</span>
    <span v-translate translate-context="avalanche_levels">level_4</span>
    <span v-translate translate-context="avalanche_levels">level_5</span>
    <span v-translate translate-context="avalanche_levels">level_na</span>
    <!-- avalanche_signs -->
    <span v-translate translate-context="avalanche_signs">no</span>
    <span v-translate translate-context="avalanche_signs">danger_sign</span>
    <span v-translate translate-context="avalanche_signs">recent_avalanche</span>
    <span v-translate translate-context="avalanche_signs">natural_avalanche</span>
    <span v-translate translate-context="avalanche_signs">accidental_avalanche</span>
    <!-- avalanche_slopes -->
    <span v-translate translate-context="avalanche_slopes">slope_lt_30</span>
    <span v-translate translate-context="avalanche_slopes">slope_30_35</span>
    <span v-translate translate-context="avalanche_slopes">slope_35_40</span>
    <span v-translate translate-context="avalanche_slopes">slope_40_45</span>
    <span v-translate translate-context="avalanche_slopes">slope_gt_45</span>
    <!-- book_types -->
    <span v-translate translate-context="book_types">topo</span>
    <span v-translate translate-context="book_types">environment</span>
    <span v-translate translate-context="book_types">historical</span>
    <span v-translate translate-context="book_types">biography</span>
    <span v-translate translate-context="book_types">photos-art</span>
    <span v-translate translate-context="book_types">novel</span>
    <span v-translate translate-context="book_types">technics</span>
    <span v-translate translate-context="book_types">tourism</span>
    <span v-translate translate-context="book_types">magazine</span>
    <!-- children_proof_types -->
    <span v-translate translate-context="children_proof_types">very_safe</span>
    <span v-translate translate-context="children_proof_types">safe</span>
    <span v-translate translate-context="children_proof_types">dangerous</span>
    <span v-translate translate-context="children_proof_types">very_dangerous</span>
    <!-- climbing_indoor_types -->
    <span v-translate translate-context="climbing_indoor_types">pitch</span>
    <span v-translate translate-context="climbing_indoor_types">bloc</span>
    <!-- climbing_outdoor_types -->
    <span v-translate translate-context="climbing_outdoor_types">single</span>
    <span v-translate translate-context="climbing_outdoor_types">multi</span>
    <span v-translate translate-context="climbing_outdoor_types">bloc</span>
    <span v-translate translate-context="climbing_outdoor_types">psicobloc</span>
    <!-- climbing_styles -->
    <span v-translate translate-context="climbing_styles">slab</span>
    <span v-translate translate-context="climbing_styles">vertical</span>
    <span v-translate translate-context="climbing_styles">overhang</span>
    <span v-translate translate-context="climbing_styles">roof</span>
    <span v-translate translate-context="climbing_styles">small_pillar</span>
    <span v-translate translate-context="climbing_styles">crack_dihedral</span>
    <!-- condition_ratings -->
    <span v-translate translate-context="condition_ratings">excellent</span>
    <span v-translate translate-context="condition_ratings">good</span>
    <span v-translate translate-context="condition_ratings">average</span>
    <span v-translate translate-context="condition_ratings">poor</span>
    <span v-translate translate-context="condition_ratings">awful</span>
    <!-- custodianship_types -->
    <span v-translate translate-context="custodianship_types">accessible_when_wardened</span>
    <span v-translate translate-context="custodianship_types">always_accessible</span>
    <span v-translate translate-context="custodianship_types">key_needed</span>
    <span v-translate translate-context="custodianship_types">no_warden</span>
    <!-- event_activities -->
    <span v-translate translate-context="event_activities">sport_climbing</span>
    <span v-translate translate-context="event_activities">multipitch_climbing</span>
    <span v-translate translate-context="event_activities">alpine_climbing</span>
    <span v-translate translate-context="event_activities">snow_ice_mixed</span>
    <span v-translate translate-context="event_activities">ice_climbing</span>
    <span v-translate translate-context="event_activities">skitouring</span>
    <span v-translate translate-context="event_activities">other</span>
    <!-- event_types -->
    <span v-translate translate-context="event_types">avalanche</span>
    <span v-translate translate-context="event_types">stone_ice_fall</span>
    <span v-translate translate-context="event_types">ice_cornice_collapse</span>
    <span v-translate translate-context="event_types">person_fall</span>
    <span v-translate translate-context="event_types">crevasse_fall</span>
    <span v-translate translate-context="event_types">physical_failure</span>
    <span v-translate translate-context="event_types">injury_without_fall</span>
    <span v-translate translate-context="event_types">blocked_person</span>
    <span v-translate translate-context="event_types">weather_event</span>
    <span v-translate translate-context="event_types">safety_operation</span>
    <span v-translate translate-context="event_types">critical_situation</span>
    <span v-translate translate-context="event_types">other</span>
    <!-- frequentation_types -->
    <span v-translate translate-context="frequentation_types">quiet</span>
    <span v-translate translate-context="frequentation_types">some</span>
    <span v-translate translate-context="frequentation_types">crowded</span>
    <span v-translate translate-context="frequentation_types">overcrowded</span>
    <!-- genders -->
    <span v-translate translate-context="genders">male</span>
    <span v-translate translate-context="genders">female</span>
    <!-- glacier_gear_types -->
    <span v-translate translate-context="glacier_gear_types">no</span>
    <span v-translate translate-context="glacier_gear_types">glacier_safety_gear</span>
    <span v-translate translate-context="glacier_gear_types">crampons_spring</span>
    <span v-translate translate-context="glacier_gear_types">crampons_req</span>
    <span v-translate translate-context="glacier_gear_types">glacier_crampons</span>
    <!-- glacier_ratings -->
    <span v-translate translate-context="glacier_ratings">easy</span>
    <span v-translate translate-context="glacier_ratings">possible</span>
    <span v-translate translate-context="glacier_ratings">difficult</span>
    <span v-translate translate-context="glacier_ratings">impossible</span>
    <!-- ground_types -->
    <span v-translate translate-context="ground_types">prairie</span>
    <span v-translate translate-context="ground_types">scree</span>
    <span v-translate translate-context="ground_types">snow</span>
    <!-- hut_status -->
    <span v-translate translate-context="hut_status">open_guarded</span>
    <span v-translate translate-context="hut_status">open_non_guarded</span>
    <span v-translate translate-context="hut_status">closed_hut</span>
    <!-- image_categories -->
    <span v-translate translate-context="image_categories">landscapes</span>
    <span v-translate translate-context="image_categories">detail</span>
    <span v-translate translate-context="image_categories">action</span>
    <span v-translate translate-context="image_categories">track</span>
    <span v-translate translate-context="image_categories">rise</span>
    <span v-translate translate-context="image_categories">descent</span>
    <span v-translate translate-context="image_categories">topo</span>
    <span v-translate translate-context="image_categories">people</span>
    <span v-translate translate-context="image_categories">fauna</span>
    <span v-translate translate-context="image_categories">flora</span>
    <span v-translate translate-context="image_categories">nivology</span>
    <span v-translate translate-context="image_categories">geology</span>
    <span v-translate translate-context="image_categories">hut</span>
    <span v-translate translate-context="image_categories">equipment</span>
    <span v-translate translate-context="image_categories">book</span>
    <span v-translate translate-context="image_categories">help</span>
    <span v-translate translate-context="image_categories">misc</span>
    <!-- image_types -->
    <span v-translate translate-context="image_types">collaborative</span>
    <span v-translate translate-context="image_types">personal</span>
    <span v-translate translate-context="image_types">copyright</span>
    <!-- langs -->
    <span v-translate translate-context="langs">fr</span>
    <span v-translate translate-context="langs">en</span>
    <span v-translate translate-context="langs">it</span>
    <span v-translate translate-context="langs">de</span>
    <span v-translate translate-context="langs">es</span>
    <span v-translate translate-context="langs">ca</span>
    <span v-translate translate-context="langs">eu</span>
    <span v-translate translate-context="langs">zh</span>
    <span v-translate translate-context="langs">sl</span>
    <!-- lift_status -->
    <span v-translate translate-context="lift_status">open</span>
    <span v-translate translate-context="lift_status">closed</span>
    <!-- paragliding_ratings -->
    <span v-translate translate-context="paragliding_ratings">1</span>
    <span v-translate translate-context="paragliding_ratings">2</span>
    <span v-translate translate-context="paragliding_ratings">3</span>
    <span v-translate translate-context="paragliding_ratings">4</span>
    <!-- parking_fee_types -->
    <span v-translate translate-context="parking_fee_types">yes</span>
    <span v-translate translate-context="parking_fee_types">seasonal</span>
    <span v-translate translate-context="parking_fee_types">no</span>
    <!-- previous_injuries -->
    <span v-translate translate-context="previous_injuries">no</span>
    <span v-translate translate-context="previous_injuries">previous_injuries_2</span>
    <!-- product_types -->
    <span v-translate translate-context="product_types">farm_sale</span>
    <span v-translate translate-context="product_types">restaurant</span>
    <span v-translate translate-context="product_types">grocery</span>
    <span v-translate translate-context="product_types">bar</span>
    <span v-translate translate-context="product_types">sport_shop</span>
    <!-- public_transportation_ratings -->
    <span v-translate translate-context="public_transportation_ratings">good service</span>
    <span v-translate translate-context="public_transportation_ratings">seasonal service</span>
    <span v-translate translate-context="public_transportation_ratings">poor service</span>
    <span v-translate translate-context="public_transportation_ratings">nearby service</span>
    <span v-translate translate-context="public_transportation_ratings">unknown service</span>
    <span v-translate translate-context="public_transportation_ratings">no service</span>
    <!-- public_transportation_types -->
    <span v-translate translate-context="public_transportation_types">train</span>
    <span v-translate translate-context="public_transportation_types">bus</span>
    <span v-translate translate-context="public_transportation_types">service_on_demand</span>
    <span v-translate translate-context="public_transportation_types">boat</span>
    <!-- qualification -->
    <span v-translate translate-context="qualification">federal_supervisor</span>
    <span v-translate translate-context="qualification">federal_trainer</span>
    <span v-translate translate-context="qualification">professional_diploma</span>
    <!-- quality_types -->
    <span v-translate translate-context="quality_types">empty</span>
    <span v-translate translate-context="quality_types">draft</span>
    <span v-translate translate-context="quality_types">medium</span>
    <span v-translate translate-context="quality_types">fine</span>
    <span v-translate translate-context="quality_types">great</span>
    <!-- rain_proof_types -->
    <span v-translate translate-context="rain_proof_types">exposed</span>
    <span v-translate translate-context="rain_proof_types">partly_protected</span>
    <span v-translate translate-context="rain_proof_types">protected</span>
    <span v-translate translate-context="rain_proof_types">inside</span>
    <!-- rock_types -->
    <span v-translate translate-context="rock_types">basalte</span>
    <span v-translate translate-context="rock_types">calcaire</span>
    <span v-translate translate-context="rock_types">conglomerat</span>
    <span v-translate translate-context="rock_types">craie</span>
    <span v-translate translate-context="rock_types">gneiss</span>
    <span v-translate translate-context="rock_types">gres</span>
    <span v-translate translate-context="rock_types">granit</span>
    <span v-translate translate-context="rock_types">migmatite</span>
    <span v-translate translate-context="rock_types">mollasse_calcaire</span>
    <span v-translate translate-context="rock_types">pouding</span>
    <span v-translate translate-context="rock_types">quartzite</span>
    <span v-translate translate-context="rock_types">rhyolite</span>
    <span v-translate translate-context="rock_types">schiste</span>
    <span v-translate translate-context="rock_types">trachyte</span>
    <span v-translate translate-context="rock_types">artificial</span>
    <!-- route_configuration_types -->
    <span v-translate translate-context="route_configuration_types">edge</span>
    <span v-translate translate-context="route_configuration_types">pillar</span>
    <span v-translate translate-context="route_configuration_types">face</span>
    <span v-translate translate-context="route_configuration_types">corridor</span>
    <span v-translate translate-context="route_configuration_types">goulotte</span>
    <span v-translate translate-context="route_configuration_types">glacier</span>
    <!-- route_types -->
    <span v-translate translate-context="route_types">return_same_way</span>
    <span v-translate translate-context="route_types">loop</span>
    <span v-translate translate-context="route_types">loop_hut</span>
    <span v-translate translate-context="route_types">traverse</span>
    <span v-translate translate-context="route_types">raid</span>
    <span v-translate translate-context="route_types">expedition</span>
    <!-- severities -->
    <span v-translate translate-context="severities">severity_no</span>
    <span v-translate translate-context="severities">1d_to_3d</span>
    <span v-translate translate-context="severities">4d_to_1m</span>
    <span v-translate translate-context="severities">1m_to_3m</span>
    <span v-translate translate-context="severities">more_than_3m</span>
    <!-- slackline_types -->
    <span v-translate translate-context="slackline_types">slackline</span>
    <span v-translate translate-context="slackline_types">highline</span>
    <span v-translate translate-context="slackline_types">waterline</span>
    <!-- snow_clearance_ratings -->
    <span v-translate translate-context="snow_clearance_ratings">often</span>
    <span v-translate translate-context="snow_clearance_ratings">sometimes</span>
    <span v-translate translate-context="snow_clearance_ratings">progressive</span>
    <span v-translate translate-context="snow_clearance_ratings">naturally</span>
    <span v-translate translate-context="snow_clearance_ratings">closed_in_winter</span>
    <span v-translate translate-context="snow_clearance_ratings">non_applicable</span>
    <!-- snow_quality_ratings -->
    <span v-translate translate-context="snow_quality_ratings">excellent</span>
    <span v-translate translate-context="snow_quality_ratings">good</span>
    <span v-translate translate-context="snow_quality_ratings">average</span>
    <span v-translate translate-context="snow_quality_ratings">poor</span>
    <span v-translate translate-context="snow_quality_ratings">awful</span>
    <!-- snow_quantity_ratings -->
    <span v-translate translate-context="snow_quantity_ratings">excellent</span>
    <span v-translate translate-context="snow_quantity_ratings">good</span>
    <span v-translate translate-context="snow_quantity_ratings">average</span>
    <span v-translate translate-context="snow_quantity_ratings">poor</span>
    <span v-translate translate-context="snow_quantity_ratings">awful</span>
    <!-- supervision -->
    <span v-translate translate-context="supervision">no_supervision</span>
    <span v-translate translate-context="supervision">federal_supervision</span>
    <span v-translate translate-context="supervision">professional_supervision</span>
    <!-- user_categories -->
    <span v-translate translate-context="user_categories">amateur</span>
    <span v-translate translate-context="user_categories">mountain_guide</span>
    <span v-translate translate-context="user_categories">mountain_leader</span>
    <span v-translate translate-context="user_categories">ski_instructor</span>
    <span v-translate translate-context="user_categories">climbing_instructor</span>
    <span v-translate translate-context="user_categories">mountainbike_instructor</span>
    <span v-translate translate-context="user_categories">paragliding_instructor</span>
    <span v-translate translate-context="user_categories">hut_warden</span>
    <span v-translate translate-context="user_categories">ski_patroller</span>
    <span v-translate translate-context="user_categories">avalanche_forecaster</span>
    <span v-translate translate-context="user_categories">club</span>
    <span v-translate translate-context="user_categories">institution</span>
    <!-- waypoint_types -->
    <span v-translate translate-context="waypoint_types">summit</span>
    <span v-translate translate-context="waypoint_types">pass</span>
    <span v-translate translate-context="waypoint_types">lake</span>
    <span v-translate translate-context="waypoint_types">waterfall</span>
    <span v-translate translate-context="waypoint_types">locality</span>
    <span v-translate translate-context="waypoint_types">bisse</span>
    <span v-translate translate-context="waypoint_types">canyon</span>
    <span v-translate translate-context="waypoint_types">access</span>
    <span v-translate translate-context="waypoint_types">climbing_outdoor</span>
    <span v-translate translate-context="waypoint_types">climbing_indoor</span>
    <span v-translate translate-context="waypoint_types">hut</span>
    <span v-translate translate-context="waypoint_types">gite</span>
    <span v-translate translate-context="waypoint_types">shelter</span>
    <span v-translate translate-context="waypoint_types">bivouac</span>
    <span v-translate translate-context="waypoint_types">camp_site</span>
    <span v-translate translate-context="waypoint_types">base_camp</span>
    <span v-translate translate-context="waypoint_types">local_product</span>
    <span v-translate translate-context="waypoint_types">paragliding_takeoff</span>
    <span v-translate translate-context="waypoint_types">paragliding_landing</span>
    <span v-translate translate-context="waypoint_types">cave</span>
    <span v-translate translate-context="waypoint_types">waterpoint</span>
    <span v-translate translate-context="waypoint_types">weather_station</span>
    <span v-translate translate-context="waypoint_types">webcam</span>
    <span v-translate translate-context="waypoint_types">virtual</span>
    <span v-translate translate-context="waypoint_types">slackline_spot</span>
    <span v-translate translate-context="waypoint_types">misc</span>
    <!-- weather_station_types -->
    <span v-translate translate-context="weather_station_types">temperature</span>
    <span v-translate translate-context="weather_station_types">wind_speed</span>
    <span v-translate translate-context="weather_station_types">wind_direction</span>
    <span v-translate translate-context="weather_station_types">humidity</span>
    <span v-translate translate-context="weather_station_types">pressure</span>
    <span v-translate translate-context="weather_station_types">precipitation</span>
    <span v-translate translate-context="weather_station_types">precipitation_heater</span>
    <span v-translate translate-context="weather_station_types">snow_height</span>
    <span v-translate translate-context="weather_station_types">insolation</span>
  </span>
</template>
