<template>
    <!-- auto-generated by tools/update-c2c-common.py -->
    <span>
        <span v-translate>access</span>
        <span v-translate>access_comment</span>
        <span v-translate>access_condition</span>
        <span v-translate>access_period</span>
        <span v-translate>access_time</span>
        <span v-translate>activities</span>
        <span v-translate>activity_rate</span>
        <span v-translate>age</span>
        <span v-translate>aid_rating</span>
        <span v-translate>anonymous</span>
        <span v-translate>area_type</span>
        <span v-translate>areas</span>
        <span v-translate>article_categories</span>
        <span v-translate>article_type</span>
        <span v-translate>articles</span>
        <span v-translate>author</span>
        <span v-translate>author_status</span>
        <span v-translate>autonomy</span>
        <span v-translate>avalanche_level</span>
        <span v-translate>avalanche_signs</span>
        <span v-translate>avalanche_slope</span>
        <span v-translate>avalanches</span>
        <span v-translate>best_periods</span>
        <span v-translate>blanket_unstaffed</span>
        <span v-translate>book_types</span>
        <span v-translate>books</span>
        <span v-translate>camera_name</span>
        <span v-translate>capacity</span>
        <span v-translate>capacity_staffed</span>
        <span v-translate>categories</span>
        <span v-translate>children_proof</span>
        <span v-translate>climbing_indoor_types</span>
        <span v-translate>climbing_outdoor_type</span>
        <span v-translate>climbing_outdoor_types</span>
        <span v-translate>climbing_rating_max</span>
        <span v-translate>climbing_rating_median</span>
        <span v-translate>climbing_rating_min</span>
        <span v-translate>climbing_styles</span>
        <span v-translate>code</span>
        <span v-translate>condition_rating</span>
        <span v-translate>conditions</span>
        <span v-translate>conditions_levels</span>
        <span v-translate>configuration</span>
        <span v-translate>custodianship</span>
        <span v-translate>date</span>
        <span v-translate>date_end</span>
        <span v-translate>date_start</span>
        <span v-translate>date_time</span>
        <span v-translate>description</span>
        <span v-translate>difficulties_height</span>
        <span v-translate>disable_comments</span>
        <span v-translate>durations</span>
        <span v-translate>editor</span>
        <span v-translate>elevation</span>
        <span v-translate>elevation_access</span>
        <span v-translate>elevation_down_snow</span>
        <span v-translate>elevation_max</span>
        <span v-translate>elevation_min</span>
        <span v-translate>elevation_up_snow</span>
        <span v-translate>engagement_rating</span>
        <span v-translate>equipment_rating</span>
        <span v-translate>equipment_ratings</span>
        <span v-translate>event_type</span>
        <span v-translate>exposition_rating</span>
        <span v-translate>exposition_rock_rating</span>
        <span v-translate>exposure_time</span>
        <span v-translate>external_resources</span>
        <span v-translate>file_size</span>
        <span v-translate>filename</span>
        <span v-translate>fnumber</span>
        <span v-translate>focal_length</span>
        <span v-translate>frequentation</span>
        <span v-translate>gas_unstaffed</span>
        <span v-translate>gear</span>
        <span v-translate>gender</span>
        <span v-translate>glacier_gear</span>
        <span v-translate>glacier_rating</span>
        <span v-translate>global_rating</span>
        <span v-translate>ground_types</span>
        <span v-translate>group_management</span>
        <span v-translate>heating_unstaffed</span>
        <span v-translate>height</span>
        <span v-translate>height_diff_access</span>
        <span v-translate>height_diff_difficulties</span>
        <span v-translate>height_diff_down</span>
        <span v-translate>height_diff_up</span>
        <span v-translate>height_max</span>
        <span v-translate>height_median</span>
        <span v-translate>height_min</span>
        <span v-translate>hiking_mtb_exposition</span>
        <span v-translate>hiking_rating</span>
        <span v-translate>hut_comment</span>
        <span v-translate>hut_status</span>
        <span v-translate>ice_rating</span>
        <span v-translate>image_categories</span>
        <span v-translate>image_type</span>
        <span v-translate>images</span>
        <span v-translate>increase_impact</span>
        <span v-translate>isbn</span>
        <span v-translate>iso_speed</span>
        <span v-translate>labande_global_rating</span>
        <span v-translate>labande_ski_rating</span>
        <span v-translate>lang</span>
        <span v-translate>langs</span>
        <span v-translate>length</span>
        <span v-translate>length_total</span>
        <span v-translate>lift_access</span>
        <span v-translate>lift_status</span>
        <span v-translate>main_waypoint_id</span>
        <span v-translate>maps_info</span>
        <span v-translate>matress_unstaffed</span>
        <span v-translate>mixed_rating</span>
        <span v-translate>modifications</span>
        <span v-translate>motivations</span>
        <span v-translate>mtb_down_rating</span>
        <span v-translate>mtb_height_diff_portages</span>
        <span v-translate>mtb_length_asphalt</span>
        <span v-translate>mtb_length_trail</span>
        <span v-translate>mtb_up_rating</span>
        <span v-translate>name</span>
        <span v-translate>nb_impacted</span>
        <span v-translate>nb_outings</span>
        <span v-translate>nb_pages</span>
        <span v-translate>nb_participants</span>
        <span v-translate>orientations</span>
        <span v-translate>other_comments</span>
        <span v-translate>outings</span>
        <span v-translate>paragliding_rating</span>
        <span v-translate>parking_fee</span>
        <span v-translate>partial_trip</span>
        <span v-translate>participant_count</span>
        <span v-translate>participants</span>
        <span v-translate>phone</span>
        <span v-translate>phone_custodian</span>
        <span v-translate>place</span>
        <span v-translate>previous_injuries</span>
        <span v-translate>product_types</span>
        <span v-translate>prominence</span>
        <span v-translate>public_transport</span>
        <span v-translate>public_transportation_rating</span>
        <span v-translate>public_transportation_types</span>
        <span v-translate>publication_date</span>
        <span v-translate>quality</span>
        <span v-translate>rain_proof</span>
        <span v-translate>reduce_impact</span>
        <span v-translate>remarks</span>
        <span v-translate>rescue</span>
        <span v-translate>risk</span>
        <span v-translate>risk_rating</span>
        <span v-translate>rock_free_rating</span>
        <span v-translate>rock_required_rating</span>
        <span v-translate>rock_types</span>
        <span v-translate>route_description</span>
        <span v-translate>route_history</span>
        <span v-translate>route_length</span>
        <span v-translate>route_study</span>
        <span v-translate>route_types</span>
        <span v-translate>routes</span>
        <span v-translate>routes_quantity</span>
        <span v-translate>safety</span>
        <span v-translate>scale</span>
        <span v-translate>severity</span>
        <span v-translate>ski_exposition</span>
        <span v-translate>ski_rating</span>
        <span v-translate>slackline_anchor1</span>
        <span v-translate>slackline_anchor2</span>
        <span v-translate>slackline_height</span>
        <span v-translate>slackline_length_max</span>
        <span v-translate>slackline_length_min</span>
        <span v-translate>slackline_type</span>
        <span v-translate>slackline_types</span>
        <span v-translate>slope</span>
        <span v-translate>snow_clearance_rating</span>
        <span v-translate>snow_quality</span>
        <span v-translate>snow_quantity</span>
        <span v-translate>snowshoe_rating</span>
        <span v-translate>summary</span>
        <span v-translate>time_management</span>
        <span v-translate>timing</span>
        <span v-translate>title</span>
        <span v-translate>training</span>
        <span v-translate>url</span>
        <span v-translate>users</span>
        <span v-translate>via_ferrata_rating</span>
        <span v-translate>waypoint_slope</span>
        <span v-translate>waypoint_type</span>
        <span v-translate>waypoints</span>
        <span v-translate>weather</span>
        <span v-translate>weather_station_types</span>
        <span v-translate>width</span>
        <span v-translate>xreports</span>
        <!-- access_conditions -->
        <span v-translate>cleared</span>
        <span v-translate>snowy</span>
        <span v-translate>closed_snow</span>
        <span v-translate>closed_cleared</span>
        <!-- access_times -->
        <span v-translate>1min</span>
        <span v-translate>5min</span>
        <span v-translate>10min</span>
        <span v-translate>15min</span>
        <span v-translate>20min</span>
        <span v-translate>30min</span>
        <span v-translate>45min</span>
        <span v-translate>1h</span>
        <span v-translate>1h30</span>
        <span v-translate>2h</span>
        <span v-translate>2h30</span>
        <span v-translate>3h</span>
        <span v-translate>3h+</span>
        <!-- activities -->
        <span v-translate>skitouring</span>
        <span v-translate>snow_ice_mixed</span>
        <span v-translate>mountain_climbing</span>
        <span v-translate>rock_climbing</span>
        <span v-translate>ice_climbing</span>
        <span v-translate>hiking</span>
        <span v-translate>snowshoeing</span>
        <span v-translate>paragliding</span>
        <span v-translate>mountain_biking</span>
        <span v-translate>via_ferrata</span>
        <span v-translate>slacklining</span>
        <!-- activity_rates -->
        <span v-translate>activity_rate_150</span>
        <span v-translate>activity_rate_50</span>
        <span v-translate>activity_rate_30</span>
        <span v-translate>activity_rate_20</span>
        <span v-translate>activity_rate_10</span>
        <span v-translate>activity_rate_5</span>
        <span v-translate>activity_rate_1</span>
        <!-- area_types -->
        <span v-translate>range</span>
        <span v-translate>admin_limits</span>
        <span v-translate>country</span>
        <!-- article_categories -->
        <span v-translate>mountain_environment</span>
        <span v-translate>gear</span>
        <span v-translate>technical</span>
        <span v-translate>topoguide_supplements</span>
        <span v-translate>soft_mobility</span>
        <span v-translate>expeditions</span>
        <span v-translate>stories</span>
        <span v-translate>c2c_meetings</span>
        <span v-translate>tags</span>
        <span v-translate>site_info</span>
        <span v-translate>association</span>
        <!-- article_types -->
        <span v-translate>collab</span>
        <span v-translate>personal</span>
        <!-- author_statuses -->
        <span v-translate>primary_impacted</span>
        <span v-translate>secondary_impacted</span>
        <span v-translate>internal_witness</span>
        <span v-translate>external_witness</span>
        <!-- autonomies -->
        <span v-translate>non_autonomous</span>
        <span v-translate>autonomous</span>
        <span v-translate>initiator</span>
        <span v-translate>expert</span>
        <!-- avalanche_levels -->
        <span v-translate>level_1</span>
        <span v-translate>level_2</span>
        <span v-translate>level_3</span>
        <span v-translate>level_4</span>
        <span v-translate>level_5</span>
        <span v-translate>level_na</span>
        <!-- avalanche_signs -->
        <span v-translate>no</span>
        <span v-translate>danger_sign</span>
        <span v-translate>recent_avalanche</span>
        <span v-translate>natural_avalanche</span>
        <span v-translate>accidental_avalanche</span>
        <!-- avalanche_slopes -->
        <span v-translate>slope_lt_30</span>
        <span v-translate>slope_30_35</span>
        <span v-translate>slope_35_40</span>
        <span v-translate>slope_40_45</span>
        <span v-translate>slope_gt_45</span>
        <!-- book_types -->
        <span v-translate>topo</span>
        <span v-translate>environment</span>
        <span v-translate>historical</span>
        <span v-translate>biography</span>
        <span v-translate>photos-art</span>
        <span v-translate>novel</span>
        <span v-translate>technics</span>
        <span v-translate>tourism</span>
        <span v-translate>magazine</span>
        <!-- children_proof_types -->
        <span v-translate>very_safe</span>
        <span v-translate>safe</span>
        <span v-translate>dangerous</span>
        <span v-translate>very_dangerous</span>
        <!-- climbing_indoor_types -->
        <span v-translate>pitch</span>
        <span v-translate>bloc</span>
        <!-- climbing_outdoor_types -->
        <span v-translate>single</span>
        <span v-translate>multi</span>
        <span v-translate>bloc</span>
        <span v-translate>psicobloc</span>
        <!-- climbing_styles -->
        <span v-translate>slab</span>
        <span v-translate>vertical</span>
        <span v-translate>overhang</span>
        <span v-translate>roof</span>
        <span v-translate>small_pillar</span>
        <span v-translate>crack_dihedral</span>
        <!-- condition_ratings -->
        <span v-translate>excellent</span>
        <span v-translate>good</span>
        <span v-translate>average</span>
        <span v-translate>poor</span>
        <span v-translate>awful</span>
        <!-- custodianship_types -->
        <span v-translate>accessible_when_wardened</span>
        <span v-translate>always_accessible</span>
        <span v-translate>key_needed</span>
        <span v-translate>no_warden</span>
        <!-- event_types -->
        <span v-translate>avalanche</span>
        <span v-translate>stone_fall</span>
        <span v-translate>falling_ice</span>
        <span v-translate>person_fall</span>
        <span v-translate>crevasse_fall</span>
        <span v-translate>roped_fall</span>
        <span v-translate>physical_failure</span>
        <span v-translate>lightning</span>
        <span v-translate>other</span>
        <!-- frequentation_types -->
        <span v-translate>quiet</span>
        <span v-translate>some</span>
        <span v-translate>crowded</span>
        <span v-translate>overcrowded</span>
        <!-- genders -->
        <span v-translate>male</span>
        <span v-translate>female</span>
        <!-- glacier_gear_types -->
        <span v-translate>no</span>
        <span v-translate>glacier_safety_gear</span>
        <span v-translate>crampons_spring</span>
        <span v-translate>crampons_req</span>
        <span v-translate>glacier_crampons</span>
        <!-- glacier_ratings -->
        <span v-translate>easy</span>
        <span v-translate>possible</span>
        <span v-translate>difficult</span>
        <span v-translate>impossible</span>
        <!-- ground_types -->
        <span v-translate>prairie</span>
        <span v-translate>scree</span>
        <span v-translate>snow</span>
        <!-- hut_status -->
        <span v-translate>open_guarded</span>
        <span v-translate>open_non_guarded</span>
        <span v-translate>closed_hut</span>
        <!-- image_categories -->
        <span v-translate>landscapes</span>
        <span v-translate>detail</span>
        <span v-translate>action</span>
        <span v-translate>track</span>
        <span v-translate>rise</span>
        <span v-translate>descent</span>
        <span v-translate>topo</span>
        <span v-translate>people</span>
        <span v-translate>fauna</span>
        <span v-translate>flora</span>
        <span v-translate>nivology</span>
        <span v-translate>geology</span>
        <span v-translate>hut</span>
        <span v-translate>equipment</span>
        <span v-translate>book</span>
        <span v-translate>help</span>
        <span v-translate>misc</span>
        <!-- image_types -->
        <span v-translate>collaborative</span>
        <span v-translate>personal</span>
        <span v-translate>copyright</span>
        <!-- langs -->
        <span v-translate>fr</span>
        <span v-translate>en</span>
        <span v-translate>it</span>
        <span v-translate>de</span>
        <span v-translate>es</span>
        <span v-translate>ca</span>
        <span v-translate>eu</span>
        <!-- lift_status -->
        <span v-translate>open</span>
        <span v-translate>closed</span>
        <!-- months -->
        <span v-translate>jan</span>
        <span v-translate>feb</span>
        <span v-translate>mar</span>
        <span v-translate>apr</span>
        <span v-translate>may</span>
        <span v-translate>jun</span>
        <span v-translate>jul</span>
        <span v-translate>aug</span>
        <span v-translate>sep</span>
        <span v-translate>oct</span>
        <span v-translate>nov</span>
        <span v-translate>dec</span>
        <!-- nb_outings -->
        <span v-translate>nb_outings_4</span>
        <span v-translate>nb_outings_9</span>
        <span v-translate>nb_outings_14</span>
        <span v-translate>nb_outings_15</span>
        <!-- parking_fee_types -->
        <span v-translate>yes</span>
        <span v-translate>seasonal</span>
        <span v-translate>no</span>
        <!-- previous_injuries -->
        <span v-translate>no</span>
        <span v-translate>previous_injuries_2</span>
        <span v-translate>previous_injuries_3</span>
        <!-- product_types -->
        <span v-translate>farm_sale</span>
        <span v-translate>restaurant</span>
        <span v-translate>grocery</span>
        <span v-translate>bar</span>
        <span v-translate>sport_shop</span>
        <!-- public_transportation_ratings -->
        <span v-translate>good service</span>
        <span v-translate>seasonal service</span>
        <span v-translate>poor service</span>
        <span v-translate>nearby service</span>
        <span v-translate>no service</span>
        <!-- public_transportation_types -->
        <span v-translate>train</span>
        <span v-translate>bus</span>
        <span v-translate>service_on_demand</span>
        <span v-translate>boat</span>
        <!-- quality_types -->
        <span v-translate>empty</span>
        <span v-translate>draft</span>
        <span v-translate>medium</span>
        <span v-translate>fine</span>
        <span v-translate>great</span>
        <!-- rain_proof_types -->
        <span v-translate>exposed</span>
        <span v-translate>partly_protected</span>
        <span v-translate>protected</span>
        <span v-translate>inside</span>
        <!-- rock_types -->
        <span v-translate>basalte</span>
        <span v-translate>calcaire</span>
        <span v-translate>conglomerat</span>
        <span v-translate>craie</span>
        <span v-translate>gneiss</span>
        <span v-translate>gres</span>
        <span v-translate>granit</span>
        <span v-translate>migmatite</span>
        <span v-translate>mollasse_calcaire</span>
        <span v-translate>pouding</span>
        <span v-translate>quartzite</span>
        <span v-translate>rhyolite</span>
        <span v-translate>schiste</span>
        <span v-translate>trachyte</span>
        <span v-translate>artificial</span>
        <!-- route_configuration_types -->
        <span v-translate>edge</span>
        <span v-translate>pillar</span>
        <span v-translate>face</span>
        <span v-translate>corridor</span>
        <span v-translate>goulotte</span>
        <span v-translate>glacier</span>
        <!-- route_types -->
        <span v-translate>return_same_way</span>
        <span v-translate>loop</span>
        <span v-translate>loop_hut</span>
        <span v-translate>traverse</span>
        <span v-translate>raid</span>
        <span v-translate>expedition</span>
        <!-- severities -->
        <span v-translate>severity_no</span>
        <span v-translate>1d_to_3d</span>
        <span v-translate>4d_to_1m</span>
        <span v-translate>1m_to_3m</span>
        <span v-translate>more_than_3m</span>
        <!-- slackline_types -->
        <span v-translate>slackline</span>
        <span v-translate>highline</span>
        <span v-translate>waterline</span>
        <!-- snow_clearance_ratings -->
        <span v-translate>often</span>
        <span v-translate>sometimes</span>
        <span v-translate>progressive</span>
        <span v-translate>naturally</span>
        <span v-translate>closed_in_winter</span>
        <span v-translate>non_applicable</span>
        <!-- user_categories -->
        <span v-translate>amateur</span>
        <span v-translate>mountain_guide</span>
        <span v-translate>mountain_leader</span>
        <span v-translate>ski_instructor</span>
        <span v-translate>climbing_instructor</span>
        <span v-translate>mountainbike_instructor</span>
        <span v-translate>paragliding_instructor</span>
        <span v-translate>hut_warden</span>
        <span v-translate>ski_patroller</span>
        <span v-translate>avalanche_forecaster</span>
        <span v-translate>club</span>
        <span v-translate>institution</span>
        <!-- waypoint_types -->
        <span v-translate>summit</span>
        <span v-translate>pass</span>
        <span v-translate>lake</span>
        <span v-translate>waterfall</span>
        <span v-translate>locality</span>
        <span v-translate>bisse</span>
        <span v-translate>canyon</span>
        <span v-translate>access</span>
        <span v-translate>climbing_outdoor</span>
        <span v-translate>climbing_indoor</span>
        <span v-translate>hut</span>
        <span v-translate>gite</span>
        <span v-translate>shelter</span>
        <span v-translate>bivouac</span>
        <span v-translate>camp_site</span>
        <span v-translate>base_camp</span>
        <span v-translate>local_product</span>
        <span v-translate>paragliding_takeoff</span>
        <span v-translate>paragliding_landing</span>
        <span v-translate>cave</span>
        <span v-translate>waterpoint</span>
        <span v-translate>weather_station</span>
        <span v-translate>webcam</span>
        <span v-translate>virtual</span>
        <span v-translate>slackline_spot</span>
        <span v-translate>misc</span>
        <!-- weather_station_types -->
        <span v-translate>temperature</span>
        <span v-translate>wind_speed</span>
        <span v-translate>wind_direction</span>
        <span v-translate>humidity</span>
        <span v-translate>pressure</span>
        <span v-translate>precipitation</span>
        <span v-translate>precipitation_heater</span>
        <span v-translate>snow_height</span>
        <span v-translate>insolation</span>
    </span>
</template>
