<template>
    <!-- Add here any string that are not present elsewhere, but are dynamiclly generated by IU-->
    <span>
        <span v-translate>Create a new route</span>
        <!-- TODO 10 types  -->

        <span v-translate>routes</span>
        <!-- TODO 10 types, plural -->

        <span v-translate>Edit in fr</span>
        <span v-translate>Edit in de</span>
        <span v-translate>Edit in it</span>
        <span v-translate>Edit in en</span>
        <span v-translate>Edit in es</span>
        <span v-translate>Edit in eu</span>
        <span v-translate>Edit in ca</span>

        <!-- strings in field.js -->
        <span v-translate>This field must be a valid ISBN.</span>
    </span>
</template>
