export default {
    "letter_types": [
        "a",
        "c",
        "i",
        "m",
        "o",
        "r",
        "u",
        "w",
        "b",
        "x"
    ],
    "attributes": {
        "frequentation_types": [
            "quiet",
            "some",
            "crowded",
            "overcrowded"
        ],
        "image_categories": [
            "landscapes",
            "detail",
            "action",
            "track",
            "rise",
            "descent",
            "topo",
            "people",
            "fauna",
            "flora",
            "nivology",
            "geology",
            "hut",
            "equipment",
            "book",
            "help",
            "misc"
        ],
        "map_editors": [
            "IGN",
            "Swisstopo",
            "Escursionista"
        ],
        "mtb_down_ratings": [
            "V1",
            "V2",
            "V3",
            "V4",
            "V5"
        ],
        "snowshoe_ratings": [
            "R1",
            "R2",
            "R3",
            "R4",
            "R5"
        ],
        "exposition_rock_ratings": [
            "E1",
            "E2",
            "E3",
            "E4",
            "E5",
            "E6"
        ],
        "risk_ratings": [
            "X1",
            "X2",
            "X3",
            "X4",
            "X5"
        ],
        "mixed_ratings": [
            "M1",
            "M2",
            "M3",
            "M3+",
            "M4",
            "M4+",
            "M5",
            "M5+",
            "M6",
            "M6+",
            "M7",
            "M7+",
            "M8",
            "M8+",
            "M9",
            "M9+",
            "M10",
            "M10+",
            "M11",
            "M11+",
            "M12",
            "M12+"
        ],
        "global_ratings": [
            "F",
            "F+",
            "PD-",
            "PD",
            "PD+",
            "AD-",
            "AD",
            "AD+",
            "D-",
            "D",
            "D+",
            "TD-",
            "TD",
            "TD+",
            "ED-",
            "ED",
            "ED+",
            "ED4",
            "ED5",
            "ED6",
            "ED7"
        ],
        "avalanche_slopes": [
            "slope_lt_30",
            "slope_30_35",
            "slope_35_40",
            "slope_40_45",
            "slope_gt_45"
        ],
        "rain_proof_types": [
            "exposed",
            "partly_protected",
            "protected",
            "inside"
        ],
        "hiking_ratings": [
            "T1",
            "T2",
            "T3",
            "T4",
            "T5"
        ],
        "public_transportation_ratings": [
            "good service",
            "seasonal service",
            "poor service",
            "nearby service",
            "no service"
        ],
        "orientation_types": [
            "N",
            "NE",
            "E",
            "SE",
            "S",
            "SW",
            "W",
            "NW"
        ],
        "months": [
            "jan",
            "feb",
            "mar",
            "apr",
            "may",
            "jun",
            "jul",
            "aug",
            "sep",
            "oct",
            "nov",
            "dec"
        ],
        "climbing_indoor_types": [
            "pitch",
            "bloc"
        ],
        "genders": [
            "male",
            "female"
        ],
        "area_types": [
            "range",
            "admin_limits",
            "country"
        ],
        "access_times": [
            "1min",
            "5min",
            "10min",
            "15min",
            "20min",
            "30min",
            "45min",
            "1h",
            "1h30",
            "2h",
            "2h30",
            "3h",
            "3h+"
        ],
        "public_transportation_types": [
            "train",
            "bus",
            "service_on_demand",
            "boat"
        ],
        "image_types": [
            "collaborative",
            "personal",
            "copyright"
        ],
        "waypoint_types": [
            "summit",
            "pass",
            "lake",
            "waterfall",
            "locality",
            "bisse",
            "canyon",
            "access",
            "climbing_outdoor",
            "climbing_indoor",
            "hut",
            "gite",
            "shelter",
            "bivouac",
            "camp_site",
            "base_camp",
            "local_product",
            "paragliding_takeoff",
            "paragliding_landing",
            "cave",
            "waterpoint",
            "weather_station",
            "webcam",
            "virtual",
            "slackline_spot",
            "misc"
        ],
        "exposition_ratings": [
            "E1",
            "E2",
            "E3",
            "E4"
        ],
        "quality_types": [
            "empty",
            "draft",
            "medium",
            "fine",
            "great"
        ],
        "weather_station_types": [
            "temperature",
            "wind_speed",
            "wind_direction",
            "humidity",
            "pressure",
            "precipitation",
            "precipitation_heater",
            "snow_height",
            "insolation"
        ],
        "hut_status": [
            "open_guarded",
            "open_non_guarded",
            "closed_hut"
        ],
        "article_categories": [
            "mountain_environment",
            "gear",
            "technical",
            "topoguide_supplements",
            "soft_mobility",
            "expeditions",
            "stories",
            "c2c_meetings",
            "tags",
            "site_info",
            "association"
        ],
        "glacier_ratings": [
            "easy",
            "possible",
            "difficult",
            "impossible"
        ],
        "activity_rates": [
            "activity_rate_150",
            "activity_rate_50",
            "activity_rate_30",
            "activity_rate_20",
            "activity_rate_10",
            "activity_rate_5",
            "activity_rate_1"
        ],
        "condition_ratings": [
            "excellent",
            "good",
            "average",
            "poor",
            "awful"
        ],
        "feed_change_types": [
            "created",
            "updated",
            "added_photos"
        ],
        "engagement_ratings": [
            "I",
            "II",
            "III",
            "IV",
            "V",
            "VI"
        ],
        "route_types": [
            "return_same_way",
            "loop",
            "loop_hut",
            "traverse",
            "raid",
            "expedition"
        ],
        "snow_clearance_ratings": [
            "often",
            "sometimes",
            "progressive",
            "naturally",
            "closed_in_winter",
            "non_applicable"
        ],
        "activities": [
            "skitouring",
            "snow_ice_mixed",
            "mountain_climbing",
            "rock_climbing",
            "ice_climbing",
            "hiking",
            "snowshoeing",
            "paragliding",
            "mountain_biking",
            "via_ferrata",
            "slacklining"
        ],
        "aid_ratings": [
            "A0",
            "A0+",
            "A1",
            "A1+",
            "A2",
            "A2+",
            "A3",
            "A3+",
            "A4",
            "A4+",
            "A5",
            "A5+"
        ],
        "paragliding_ratings": [
            "1",
            "2",
            "3",
            "4",
            "5"
        ],
        "autonomies": [
            "non_autonomous",
            "autonomous",
            "initiator",
            "expert"
        ],
        "equipment_ratings": [
            "P1",
            "P1+",
            "P2",
            "P2+",
            "P3",
            "P3+",
            "P4",
            "P4+"
        ],
        "mtb_up_ratings": [
            "M1",
            "M2",
            "M3",
            "M4",
            "M5"
        ],
        "author_statuses": [
            "primary_impacted",
            "secondary_impacted",
            "internal_witness",
            "external_witness"
        ],
        "ice_ratings": [
            "1",
            "2",
            "3",
            "3+",
            "4",
            "4+",
            "5",
            "5+",
            "6",
            "6+",
            "7",
            "7+"
        ],
        "user_categories": [
            "amateur",
            "mountain_guide",
            "mountain_leader",
            "ski_instructor",
            "climbing_instructor",
            "mountainbike_instructor",
            "paragliding_instructor",
            "hut_warden",
            "ski_patroller",
            "avalanche_forecaster",
            "club",
            "institution"
        ],
        "book_types": [
            "topo",
            "environment",
            "historical",
            "biography",
            "photos-art",
            "novel",
            "technics",
            "tourism",
            "magazine"
        ],
        "map_scales": [
            "25000",
            "50000",
            "100000"
        ],
        "parking_fee_types": [
            "yes",
            "seasonal",
            "no"
        ],
        "children_proof_types": [
            "very_safe",
            "safe",
            "dangerous",
            "very_dangerous"
        ],
        "previous_injuries": [
            "no",
            "previous_injuries_2",
            "previous_injuries_3"
        ],
        "ski_ratings": [
            "1.1",
            "1.2",
            "1.3",
            "2.1",
            "2.2",
            "2.3",
            "3.1",
            "3.2",
            "3.3",
            "4.1",
            "4.2",
            "4.3",
            "5.1",
            "5.2",
            "5.3",
            "5.4",
            "5.5",
            "5.6"
        ],
        "avalanche_signs": [
            "no",
            "danger_sign",
            "recent_avalanche",
            "natural_avalanche",
            "accidental_avalanche"
        ],
        "route_configuration_types": [
            "edge",
            "pillar",
            "face",
            "corridor",
            "goulotte",
            "glacier"
        ],
        "mailinglists": [
            "avalanche",
            "lawinen",
            "valanghe",
            "avalanche.en",
            "meteofrance-38",
            "meteofrance-74",
            "meteofrance-73",
            "meteofrance-04",
            "meteofrance-05",
            "meteofrance-06",
            "meteofrance-31",
            "meteofrance-64",
            "meteofrance-65",
            "meteofrance-66",
            "meteofrance-09",
            "meteofrance-andorre",
            "meteofrance-2a",
            "meteofrance-2b",
            "aran",
            "catalunya"
        ],
        "product_types": [
            "farm_sale",
            "restaurant",
            "grocery",
            "bar",
            "sport_shop"
        ],
        "climbing_ratings": [
            "2",
            "3a",
            "3b",
            "3c",
            "4a",
            "4b",
            "4c",
            "5a",
            "5a+",
            "5b",
            "5b+",
            "5c",
            "5c+",
            "6a",
            "6a+",
            "6b",
            "6b+",
            "6c",
            "6c+",
            "7a",
            "7a+",
            "7b",
            "7b+",
            "7c",
            "7c+",
            "8a",
            "8a+",
            "8b",
            "8b+",
            "8c",
            "8c+",
            "9a",
            "9a+",
            "9b",
            "9b+",
            "9c",
            "9c+"
        ],
        "glacier_gear_types": [
            "no",
            "glacier_safety_gear",
            "crampons_spring",
            "crampons_req",
            "glacier_crampons"
        ],
        "slackline_types": [
            "slackline",
            "highline",
            "waterline"
        ],
        "name": "attributes",
        "climbing_outdoor_types": [
            "single",
            "multi",
            "bloc",
            "psicobloc"
        ],
        "labande_ski_ratings": [
            "S1",
            "S2",
            "S3",
            "S4",
            "S5",
            "S6",
            "S7"
        ],
        "rock_types": [
            "basalte",
            "calcaire",
            "conglomerat",
            "craie",
            "gneiss",
            "gres",
            "granit",
            "migmatite",
            "mollasse_calcaire",
            "pouding",
            "quartzite",
            "rhyolite",
            "schiste",
            "trachyte",
            "artificial"
        ],
        "climbing_styles": [
            "slab",
            "vertical",
            "overhang",
            "roof",
            "small_pillar",
            "crack_dihedral"
        ],
        "severities": [
            "severity_no",
            "1d_to_3d",
            "4d_to_1m",
            "1m_to_3m",
            "more_than_3m"
        ],
        "ground_types": [
            "prairie",
            "scree",
            "snow"
        ],
        "custodianship_types": [
            "accessible_when_wardened",
            "always_accessible",
            "key_needed",
            "no_warden"
        ],
        "event_types": [
            "avalanche",
            "stone_fall",
            "falling_ice",
            "person_fall",
            "crevasse_fall",
            "roped_fall",
            "physical_failure",
            "lightning",
            "other"
        ],
        "avalanche_levels": [
            "level_1",
            "level_2",
            "level_3",
            "level_4",
            "level_5",
            "level_na"
        ],
        "lift_status": [
            "open",
            "closed"
        ],
        "access_conditions": [
            "cleared",
            "snowy",
            "closed_snow",
            "closed_cleared"
        ],
        "langs": [
            "fr",
            "en",
            "it",
            "de",
            "es",
            "ca",
            "eu"
        ],
        "via_ferrata_ratings": [
            "K1",
            "K2",
            "K3",
            "K4",
            "K5",
            "K6"
        ],
        "article_types": [
            "collab",
            "personal"
        ],
        "route_duration_types": [
            "1",
            "2",
            "3",
            "4",
            "5",
            "6",
            "7",
            "8",
            "9",
            "10",
            "10+"
        ],
        "nb_outings": [
            "nb_outings_4",
            "nb_outings_9",
            "nb_outings_14",
            "nb_outings_15"
        ]
    },
    "sortable_search_attributes": {
        "name": "sortable_search_attributes",
        "sortable_engagement_ratings": {
            "VI": 5,
            "V": 4,
            "IV": 3,
            "III": 2,
            "II": 1,
            "I": 0
        },
        "sortable_exposition_rock_ratings": {
            "E5": 4,
            "E3": 2,
            "E2": 1,
            "E4": 3,
            "E6": 5,
            "E1": 0
        },
        "sortable_equipment_ratings": {
            "P4+": 7,
            "P1+": 1,
            "P2+": 3,
            "P1": 0,
            "P2": 2,
            "P4": 6,
            "P3": 4,
            "P3+": 5
        },
        "sortable_condition_ratings": {
            "good": 1,
            "poor": 3,
            "awful": 4,
            "excellent": 0,
            "average": 2
        },
        "sortable_labande_ski_ratings": {
            "S4": 3,
            "S1": 0,
            "S2": 1,
            "S7": 6,
            "S3": 2,
            "S5": 4,
            "S6": 5
        },
        "sortable_ice_ratings": {
            "5+": 7,
            "7": 10,
            "4": 4,
            "7+": 11,
            "6+": 9,
            "4+": 5,
            "1": 0,
            "3": 2,
            "2": 1,
            "6": 8,
            "5": 6,
            "3+": 3
        },
        "sortable_severities": {
            "1m_to_3m": 3,
            "more_than_3m": 4,
            "4d_to_1m": 2,
            "1d_to_3d": 1,
            "severity_no": 0
        },
        "sortable_via_ferrata_ratings": {
            "K3": 2,
            "K5": 4,
            "K2": 1,
            "K1": 0,
            "K4": 3,
            "K6": 5
        },
        "sortable_global_ratings": {
            "D-": 8,
            "TD-": 11,
            "TD+": 13,
            "F": 0,
            "PD+": 4,
            "F+": 1,
            "AD+": 7,
            "ED+": 16,
            "TD": 12,
            "ED6": 19,
            "ED": 15,
            "D+": 10,
            "PD-": 2,
            "D": 9,
            "PD": 3,
            "ED-": 14,
            "AD-": 5,
            "ED4": 17,
            "ED5": 18,
            "ED7": 20,
            "AD": 6
        },
        "sortable_frequentation_types": {
            "quiet": 0,
            "some": 1,
            "overcrowded": 3,
            "crowded": 2
        },
        "sortable_mtb_up_ratings": {
            "M2": 1,
            "M4": 3,
            "M1": 0,
            "M5": 4,
            "M3": 2
        },
        "sortable_exposition_ratings": {
            "E3": 2,
            "E1": 0,
            "E2": 1,
            "E4": 3
        },
        "sortable_route_duration_types": {
            "8": 7,
            "9": 8,
            "1": 0,
            "7": 6,
            "4": 3,
            "3": 2,
            "2": 1,
            "6": 5,
            "5": 4,
            "10+": 10,
            "10": 9
        },
        "sortable_hiking_ratings": {
            "T4": 3,
            "T2": 1,
            "T5": 4,
            "T3": 2,
            "T1": 0
        },
        "sortable_access_times": {
            "5min": 1,
            "15min": 3,
            "1h30": 8,
            "3h+": 12,
            "10min": 2,
            "20min": 4,
            "2h30": 10,
            "1min": 0,
            "1h": 7,
            "2h": 9,
            "30min": 5,
            "3h": 11,
            "45min": 6
        },
        "sortable_risk_ratings": {
            "X5": 4,
            "X3": 2,
            "X1": 0,
            "X2": 1,
            "X4": 3
        },
        "sortable_ski_ratings": {
            "1.2": 1,
            "2.3": 5,
            "4.1": 9,
            "3.1": 6,
            "5.1": 12,
            "2.2": 4,
            "5.4": 15,
            "1.3": 2,
            "4.3": 11,
            "5.3": 14,
            "5.2": 13,
            "5.6": 17,
            "1.1": 0,
            "2.1": 3,
            "3.3": 8,
            "3.2": 7,
            "5.5": 16,
            "4.2": 10
        },
        "sortable_mtb_down_ratings": {
            "V4": 3,
            "V1": 0,
            "V2": 1,
            "V3": 2,
            "V5": 4
        },
        "sortable_snowshoe_ratings": {
            "R1": 0,
            "R2": 1,
            "R4": 3,
            "R5": 4,
            "R3": 2
        },
        "sortable_quality_types": {
            "medium": 2,
            "great": 4,
            "empty": 0,
            "fine": 3,
            "draft": 1
        },
        "sortable_mixed_ratings": {
            "M6": 8,
            "M7+": 11,
            "M4": 4,
            "M5": 6,
            "M2": 1,
            "M7": 10,
            "M5+": 7,
            "M10+": 17,
            "M11+": 19,
            "M11": 18,
            "M8+": 13,
            "M12+": 21,
            "M1": 0,
            "M9": 14,
            "M9+": 15,
            "M10": 16,
            "M8": 12,
            "M6+": 9,
            "M4+": 5,
            "M3+": 3,
            "M3": 2,
            "M12": 20
        },
        "sortable_paragliding_ratings": {
            "3": 2,
            "2": 1,
            "5": 4,
            "1": 0,
            "4": 3
        },
        "sortable_climbing_ratings": {
            "5a": 7,
            "6b+": 16,
            "8a+": 26,
            "5b+": 10,
            "7b+": 22,
            "4c": 6,
            "8c+": 30,
            "6c+": 18,
            "9b": 33,
            "4a": 4,
            "7a+": 20,
            "6c": 17,
            "7c": 23,
            "8b+": 28,
            "9a": 31,
            "8a": 25,
            "8c": 29,
            "6a": 13,
            "7a": 19,
            "3c": 3,
            "7b": 21,
            "5a+": 8,
            "5c": 11,
            "5b": 9,
            "9c+": 36,
            "9c": 35,
            "5c+": 12,
            "8b": 27,
            "4b": 5,
            "6a+": 14,
            "9b+": 34,
            "3a": 1,
            "9a+": 32,
            "6b": 15,
            "7c+": 24,
            "2": 0,
            "3b": 2
        },
        "sortable_glacier_ratings": {
            "possible": 1,
            "difficult": 2,
            "easy": 0,
            "impossible": 3
        },
        "sortable_aid_ratings": {
            "A0": 0,
            "A4": 8,
            "A3+": 7,
            "A4+": 9,
            "A2": 4,
            "A1": 2,
            "A5": 10,
            "A3": 6,
            "A0+": 1,
            "A2+": 5,
            "A5+": 11,
            "A1+": 3
        },
        "sortable_avalanche_slopes": {
            "slope_gt_45": 4,
            "slope_lt_30": 0,
            "slope_30_35": 1,
            "slope_35_40": 2,
            "slope_40_45": 3
        },
        "sortable_avalanche_levels": {
            "level_5": 5,
            "level_3": 3,
            "level_4": 4,
            "level_na": 0,
            "level_1": 1,
            "level_2": 2
        }
    },
    "fields": {
        "map": {
            "listing": [
                "locales.title",
                "code",
                "editor"
            ],
            "required": [
                "locales",
                "locales.title",
                "geometry",
                "geometry.geom_detail"
            ],
            "fields": [
                "locales.title",
                "geometry.geom_detail",
                "code",
                "scale",
                "editor"
            ]
        },
        "xreport": {
            "listing": [
                "locales",
                "locales.title",
                "geometry",
                "geometry.geom",
                "elevation",
                "date",
                "event_type",
                "activities",
                "nb_participants",
                "nb_impacted",
                "avalanche_level",
                "avalanche_slope",
                "severity",
                "quality"
            ],
            "required": [
                "locales",
                "locales.title",
                "geometry.geom"
            ],
            "fields": [
                "locales",
                "locales.title",
                "locales.summary",
                "locales.description",
                "locales.place",
                "locales.route_study",
                "locales.conditions",
                "locales.training",
                "locales.motivations",
                "locales.group_management",
                "locales.risk",
                "locales.time_management",
                "locales.safety",
                "locales.reduce_impact",
                "locales.modifications",
                "locales.other_comments",
                "geometry",
                "geometry.geom",
                "elevation",
                "date",
                "event_type",
                "activities",
                "nb_participants",
                "nb_impacted",
                "rescue",
                "avalanche_level",
                "avalanche_slope",
                "severity",
                "author_status",
                "activity_rate",
                "nb_outings",
                "age",
                "gender",
                "previous_injuries",
                "autonomy",
                "disable_comments",
                "anonymous",
                "quality"
            ]
        },
        "outing": {
            "hiking": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "hiking_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "hiking_rating"
                ]
            },
            "rock_climbing": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "global_rating",
                    "equipment_rating",
                    "rock_free_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "global_rating",
                    "equipment_rating",
                    "rock_free_rating"
                ]
            },
            "slacklining": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality"
                ]
            },
            "via_ferrata": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "via_ferrata_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "via_ferrata_rating"
                ]
            },
            "snow_ice_mixed": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "height_diff_difficulties",
                    "global_rating",
                    "engagement_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "elevation_up_snow",
                    "elevation_down_snow",
                    "snow_quantity",
                    "snow_quality",
                    "glacier_rating",
                    "avalanche_signs",
                    "locales.avalanches",
                    "height_diff_difficulties",
                    "global_rating",
                    "engagement_rating"
                ]
            },
            "mountain_biking": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "mtb_up_rating",
                    "mtb_down_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "mtb_up_rating",
                    "mtb_down_rating"
                ]
            },
            "mountain_climbing": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "global_rating",
                    "engagement_rating",
                    "height_diff_difficulties"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "elevation_up_snow",
                    "elevation_down_snow",
                    "snow_quantity",
                    "snow_quality",
                    "glacier_rating",
                    "global_rating",
                    "engagement_rating",
                    "height_diff_difficulties"
                ]
            },
            "ice_climbing": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "ice_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "elevation_up_snow",
                    "elevation_down_snow",
                    "snow_quantity",
                    "snow_quality",
                    "avalanche_signs",
                    "locales.avalanches",
                    "ice_rating"
                ]
            },
            "snowshoeing": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "snowshoe_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "elevation_up_snow",
                    "elevation_down_snow",
                    "snow_quantity",
                    "snow_quality",
                    "glacier_rating",
                    "avalanche_signs",
                    "locales.avalanches",
                    "snowshoe_rating"
                ]
            },
            "paragliding": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality"
                ]
            },
            "skitouring": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "elevation_max",
                    "height_diff_up",
                    "condition_rating",
                    "quality",
                    "ski_rating",
                    "labande_global_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "date_start",
                    "date_end"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.participants",
                    "locales.access_comment",
                    "locales.weather",
                    "locales.timing",
                    "locales.conditions_levels",
                    "locales.conditions",
                    "locales.hut_comment",
                    "locales.route_description",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "date_start",
                    "date_end",
                    "frequentation",
                    "participant_count",
                    "elevation_min",
                    "elevation_max",
                    "elevation_access",
                    "height_diff_up",
                    "height_diff_down",
                    "length_total",
                    "partial_trip",
                    "public_transport",
                    "access_condition",
                    "lift_status",
                    "condition_rating",
                    "hut_status",
                    "disable_comments",
                    "quality",
                    "elevation_up_snow",
                    "elevation_down_snow",
                    "snow_quantity",
                    "snow_quality",
                    "glacier_rating",
                    "avalanche_signs",
                    "locales.avalanches",
                    "ski_rating",
                    "labande_global_rating"
                ]
            }
        },
        "area": {
            "listing": [
                "locales.title",
                "area_type"
            ],
            "required": [
                "locales",
                "locales.title",
                "geometry",
                "geometry.geom_detail",
                "area_type"
            ],
            "fields": [
                "locales.title",
                "geometry.geom_detail",
                "area_type",
                "quality"
            ]
        },
        "article": {
            "listing": [
                "locales",
                "locales.title",
                "locales.summary",
                "categories",
                "activities",
                "quality",
                "article_type"
            ],
            "required": [
                "locales",
                "locales.title",
                "article_type"
            ],
            "fields": [
                "locales.title",
                "locales.summary",
                "locales.description",
                "locales.lang",
                "activities",
                "categories",
                "quality",
                "article_type"
            ]
        },
        "image": {
            "listing": [
                "locales.title",
                "geometry.geom",
                "filename",
                "author"
            ],
            "required": [
                "locales",
                "image_type"
            ],
            "fields": [
                "locales.title",
                "locales.summary",
                "locales.description",
                "geometry.geom",
                "activities",
                "categories",
                "image_type",
                "author",
                "elevation",
                "height",
                "width",
                "file_size",
                "filename",
                "camera_name",
                "exposure_time",
                "focal_length",
                "fnumber",
                "iso_speed",
                "quality"
            ]
        },
        "profile": {
            "listing": [
                "categories",
                "activities"
            ],
            "required": [],
            "fields": [
                "locales.title",
                "geometry.geom",
                "activities",
                "categories"
            ]
        },
        "book": {
            "listing": [
                "locales",
                "locales.title",
                "activities",
                "author",
                "quality",
                "book_types"
            ],
            "required": [
                "locales",
                "locales.title",
                "book_types"
            ],
            "fields": [
                "locales.title",
                "locales.summary",
                "locales.description",
                "locales.lang",
                "author",
                "editor",
                "activities",
                "url",
                "isbn",
                "book_types",
                "publication_date",
                "langs",
                "nb_pages"
            ]
        },
        "waypoint": {
            "waterpoint": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "pass": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "canyon": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "access": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access",
                    "locales.access_period",
                    "elevation_min",
                    "public_transportation_types",
                    "public_transportation_rating",
                    "snow_clearance_rating",
                    "lift_access",
                    "parking_fee"
                ]
            },
            "bivouac": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "capacity"
                ]
            },
            "webcam": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "url"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "url"
                ]
            },
            "weather_station": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "url"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "weather_station_types",
                    "url"
                ]
            },
            "climbing_indoor": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.access",
                    "geometry.geom",
                    "height_max",
                    "height_min",
                    "height_median",
                    "routes_quantity",
                    "climbing_indoor_types",
                    "url",
                    "phone",
                    "climbing_styles",
                    "climbing_rating_max",
                    "climbing_rating_min",
                    "climbing_rating_median"
                ]
            },
            "cave": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "summit": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "prominence"
                ]
            },
            "locality": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "hut": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "custodianship"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access",
                    "locales.access_period",
                    "capacity",
                    "capacity_staffed",
                    "url",
                    "phone",
                    "phone_custodian",
                    "custodianship",
                    "matress_unstaffed",
                    "blanket_unstaffed",
                    "gas_unstaffed",
                    "heating_unstaffed"
                ]
            },
            "virtual": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "waterfall": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "gite": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "custodianship"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access_period",
                    "capacity",
                    "capacity_staffed",
                    "url",
                    "phone",
                    "phone_custodian",
                    "custodianship"
                ]
            },
            "shelter": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "capacity",
                    "matress_unstaffed",
                    "blanket_unstaffed",
                    "gas_unstaffed",
                    "heating_unstaffed"
                ]
            },
            "climbing_outdoor": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access",
                    "locales.access_period",
                    "height_max",
                    "height_min",
                    "height_median",
                    "routes_quantity",
                    "climbing_outdoor_types",
                    "rain_proof",
                    "children_proof",
                    "rock_types",
                    "orientations",
                    "best_periods",
                    "url",
                    "climbing_styles",
                    "access_time",
                    "climbing_rating_max",
                    "climbing_rating_min",
                    "climbing_rating_median",
                    "equipment_ratings"
                ]
            },
            "base_camp": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "lake": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "misc": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "bisse": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality"
                ]
            },
            "slackline_spot": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type",
                    "slackline_types",
                    "slackline_length_min",
                    "slackline_length_max"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "slackline_types"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "slackline_types",
                    "slackline_length_min",
                    "slackline_length_max",
                    "locales.access",
                    "access_time",
                    "best_periods",
                    "orientations"
                ]
            },
            "camp_site": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "custodianship"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access_period",
                    "capacity",
                    "capacity_staffed",
                    "url",
                    "phone",
                    "phone_custodian",
                    "custodianship"
                ]
            },
            "paragliding_takeoff": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "length",
                    "slope",
                    "ground_types",
                    "paragliding_rating",
                    "exposition_rating",
                    "orientations"
                ]
            },
            "paragliding_landing": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "length",
                    "slope",
                    "ground_types",
                    "paragliding_rating",
                    "exposition_rating",
                    "orientations"
                ]
            },
            "local_product": {
                "listing": [
                    "locales.title",
                    "locales.summary",
                    "geometry.geom",
                    "elevation",
                    "quality",
                    "waypoint_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "geometry",
                    "geometry.geom",
                    "elevation",
                    "product_types"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "geometry.geom",
                    "elevation",
                    "maps_info",
                    "quality",
                    "locales.access",
                    "locales.access_period",
                    "product_types",
                    "url",
                    "phone"
                ]
            }
        },
        "route": {
            "hiking": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "hiking_rating",
                    "hiking_mtb_exposition"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "route_length",
                    "glacier_gear",
                    "hiking_rating",
                    "hiking_mtb_exposition"
                ]
            },
            "rock_climbing": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "exposition_rock_rating",
                    "rock_free_rating",
                    "rock_required_rating",
                    "aid_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "difficulties_height",
                    "glacier_gear",
                    "configuration",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "exposition_rock_rating",
                    "rock_free_rating",
                    "rock_required_rating",
                    "aid_rating",
                    "rock_types",
                    "climbing_outdoor_type"
                ]
            },
            "slacklining": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "route_length",
                    "slackline_height",
                    "activities",
                    "quality",
                    "orientations",
                    "slackline_type"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities",
                    "slackline_type",
                    "route_length"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "lift_access",
                    "orientations",
                    "main_waypoint_id",
                    "quality",
                    "slackline_type",
                    "slackline_height",
                    "route_length",
                    "locales.slackline_anchor1",
                    "locales.slackline_anchor2"
                ]
            },
            "via_ferrata": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "via_ferrata_rating",
                    "engagement_rating",
                    "equipment_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "route_length",
                    "difficulties_height",
                    "configuration",
                    "engagement_rating",
                    "equipment_rating",
                    "via_ferrata_rating",
                    "rock_types"
                ]
            },
            "snow_ice_mixed": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "ice_rating",
                    "mixed_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "locales.slope",
                    "route_length",
                    "difficulties_height",
                    "glacier_gear",
                    "configuration",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "ice_rating",
                    "mixed_rating",
                    "rock_types"
                ]
            },
            "mountain_biking": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "mtb_down_rating",
                    "mtb_up_rating",
                    "hiking_mtb_exposition"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "route_length",
                    "hiking_mtb_exposition",
                    "mtb_up_rating",
                    "mtb_down_rating",
                    "mtb_length_asphalt",
                    "mtb_length_trail",
                    "mtb_height_diff_portages"
                ]
            },
            "mountain_climbing": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "exposition_rock_rating",
                    "rock_free_rating",
                    "rock_required_rating",
                    "aid_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "difficulties_height",
                    "glacier_gear",
                    "configuration",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "exposition_rock_rating",
                    "rock_free_rating",
                    "rock_required_rating",
                    "aid_rating",
                    "rock_types"
                ]
            },
            "ice_climbing": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "ice_rating",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "mixed_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "locales.slope",
                    "difficulties_height",
                    "glacier_gear",
                    "global_rating",
                    "engagement_rating",
                    "risk_rating",
                    "equipment_rating",
                    "ice_rating",
                    "mixed_rating"
                ]
            },
            "snowshoeing": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "snowshoe_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "locales.slope",
                    "route_length",
                    "glacier_gear",
                    "configuration",
                    "snowshoe_rating"
                ]
            },
            "skitouring": {
                "listing": [
                    "locales.title",
                    "locales.title_prefix",
                    "locales.summary",
                    "geometry.geom",
                    "geometry.has_geom_detail",
                    "elevation_max",
                    "elevation_min",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_difficulties",
                    "activities",
                    "quality",
                    "orientations",
                    "ski_rating",
                    "ski_exposition",
                    "labande_ski_rating",
                    "labande_global_rating"
                ],
                "required": [
                    "locales",
                    "locales.title",
                    "activities"
                ],
                "fields": [
                    "locales.title",
                    "locales.summary",
                    "locales.description",
                    "locales.gear",
                    "locales.remarks",
                    "locales.external_resources",
                    "locales.route_history",
                    "locales.title_prefix",
                    "geometry.geom",
                    "geometry.geom_detail",
                    "activities",
                    "elevation_min",
                    "elevation_max",
                    "height_diff_up",
                    "height_diff_down",
                    "height_diff_access",
                    "height_diff_difficulties",
                    "lift_access",
                    "route_types",
                    "orientations",
                    "durations",
                    "main_waypoint_id",
                    "quality",
                    "locales.slope",
                    "route_length",
                    "glacier_gear",
                    "configuration",
                    "ski_rating",
                    "ski_exposition",
                    "labande_ski_rating",
                    "labande_global_rating"
                ]
            }
        }
    }
}