import common from './common.js'


/* shorthand helpers */
const attrs = common.attributes;

//shorthand for true only properties (missing prop means false)
const required=true;
const disabled=true;
const multiple=true;


//TODO : geom, longlat, condiction_levels

export default {
    access:{type:"markdown", parent:"locales"},
    access_comment:{type:"markdown", parent:"locales"},
    access_condition:{values:attrs.access_conditions},
    access_period:{type:"markdown", parent:"locales"},
    access_time:{values:attrs.access_times},
    activities:{values:attrs.activities, multiple, required, queryMode:"activities", helper:"activities"},
    activity_rate:{values:attrs.activity_rates},
    age:{type:"number", min:0, max:120, units:"years"},
    aid_rating:{values:attrs.aid_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"aid_rating"},
    anonymous:{type:"boolean"},
    area_type:{values:attrs.area_types, required},
    article_categories:{name:"categories", values:attrs.article_categories, multiple, required},
    article_type:{values:attrs.article_types, required},
    articles:{type:"document", parent:"associations", documentType:"article", multiple },
    author:{minLength:2, i18n:false},
    author_status:{values:attrs.author_statuses, helper:"author_status"},
    autonomy:{values:attrs.autonomies, helper:"autonomy"},
    avalanche_level:{values:attrs.avalanche_levels, helper:"avalanche_level"},
    avalanche_signs:{values:attrs.avalanche_signs, multiple, helper:"avalanche_signs"},
    avalanche_slope:{values:attrs.avalanche_slopes, helper:"avalanche_slope"},
    avalanches:{type:"markdown", parent:"locales"},
    best_periods:{values:attrs.months, multiple},
    blanket_unstaffed:{values:[true, false, null]},
    book_types:{values:attrs.book_types, multiple, required},
    books:{type:"document", parent:"associations", documentType:"book", multiple },
    camera_name:{type:"text"},
    capacity:{type:"number", min:0, max:9999},
    capacity_staffed:{type:"number", min:0, max:9999},
    categories:{values:attrs.user_categories, multiple},
    children_proof:{values:attrs.children_proof_types},
    climbing_indoor_types:{values:attrs.climbing_indoor_types, multiple},
    climbing_outdoor_type:{values:attrs.climbing_outdoor_types},
    climbing_outdoor_types:{values:attrs.climbing_outdoor_types, multiple},
    climbing_rating_max:{values:attrs.climbing_ratings, i18n:false},
    climbing_rating_median:{values:attrs.climbing_ratings, i18n:false},
    climbing_rating_min:{values:attrs.climbing_ratings, i18n:false},
    climbing_styles:{values:attrs.climbing_styles, multiple},
    code:{type:"text"},
    condition_rating:{values:attrs.condition_ratings, queryMode:"valuesRangeSlider", helper:"condition_rating"},
    conditions:{type:"markdown", parent:"locales", helper:"route_configuration_types"},
    configuration:{values:attrs.route_configuration_types, multiple},
    custodianship:{values:attrs.custodianship_types},
    date:{type:"date"},
    date_end:{type:"date", required},
    date_start:{type:"date", required},
    date_time:{type:"date_time"}, // wasn't in common... //TODO : max:today
    description:{type:"markdown", parent:"locales"},
    difficulties_height:{type:"number", min:0, max:9999, unit:"m", helper:"difficulties_height"},
    disable_comments:{type:"boolean"},
    durations:{values:attrs.route_duration_types, multiple, i18n:false},
    editor:{minLength:2},
    elevation:{type:"number", min:0, max:9999, unit:"m"},
    elevation_access:{type:"number", min:0, max:9999, unit:"m"},
    elevation_down_snow:{type:"number", min:0, max:9999, unit:"m", helper:"elevation_down_snow"},
    elevation_max:{type:"number", min:0, max:9999, unit:"m"},
    elevation_min:{type:"number", min:0, max:9999, unit:"m"},
    elevation_up_snow:{type:"number", min:0, max:9999, unit:"m", helper:"elevation_up_snow"},
    engagement_rating:{values:attrs.engagement_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"engagement_rating"},
    equipment_rating:{values:attrs.equipment_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"equipment_rating"},
    equipment_ratings:{values:attrs.equipment_ratings, multiple, i18n:false, helper:"equipment_rating"}, // for waypoints
    event_type:{values:attrs.event_types, multiple, helper:"event_type"},
    exposition_rating:{values:attrs.exposition_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"exposition_rating"},
    exposition_rock_rating:{values:attrs.exposition_rock_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"exposition_rock_rating"},
    exposure_time:{type:"number",min:0, max:0, unit:"ms"},
    external_resources:{type:"markdown", parent:"locales"},
    file_size:{type:"number",disabled},
    filename:{type:"text", disabled},
    fnumber:{type:"text"},
    focal_length:{type:"number",min:1, unit:"mm"},
    frequentation:{values:attrs.frequentation_types, helper:"frequentation"},
    gas_unstaffed:{values:[true, false, null]},
    gear:{type:"markdown", parent:"locales", helper:"specific gear"},
    gender:{values:attrs.genders},
    glacier_gear:{values:attrs.glacier_gear_types},
    glacier_rating:{values:attrs.glacier_ratings, queryMode:"valuesRangeSlider", helper:"glacier_rating"},
    global_rating:{values:attrs.global_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"global_rating"},
    ground_types:{values:attrs.ground_types, multiple},
    group_management:{type:"markdown", parent:"locales"},
    heating_unstaffed:{values:[true, false, null]},
    height:{type:"number", disabled},
    height_diff_access:{type:"number", min:0, max:3000, unit:"m", helper:"height_diff_access"},
    height_diff_difficulties:{type:"number", min:0, max:3000, unit:"m", helper:"height_diff_difficulties"},
    height_diff_down:{type:"number", min:0, max:9999, unit:"m", helper:"height_diff_down"},
    height_diff_up:{type:"number", min:0, max:9999, unit:"m", helper:"height_diff_up"},
    height_max:{type:"number", min:0, max:9999, unit:"m"},
    height_median:{type:"number", min:0, max:9999, unit:"m"},
    height_min:{type:"number", min:0, max:9999, unit:"m"},
    hiking_mtb_exposition:{values:attrs.exposition_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"hiking_mtb_exposition"},
    hiking_rating:{values:attrs.hiking_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"hiking_rating"},
    hut_comment:{type:"markdown", parent:"locales"},
    hut_status:{values:attrs.hut_status},
    lang:{parent:"locales", values:attrs.langs},
    ice_rating:{values:attrs.ice_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"ice_rating"},
    image_categories:{name:"categories", values:attrs.image_categories, multiple},
    image_type:{values:attrs.image_types, required},
    increase_impact:{type:"markdown", parent:"locales", helper:"increase_impact"},
    isbn:{minLength:9, maxLength:17},
    iso_speed:{type:"number", min:1, unit:"ISO"},
    labande_global_rating:{values:attrs.global_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"labande_global_rating"},
    labande_ski_rating:{values:attrs.labande_ski_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"labande_ski_rating"},
    langs:{values:attrs.langs, multiple}, //TODO
    length:{type:"number", min:0, max:9999, unit:"m"},
    length_total:{type:"number", min:0, unit:"km", queryMode:"input"},
    lift_access:{values:[true, false, null], i18n:false},
    lift_status:{values:attrs.lift_status},
    main_waypoint_id:{}, //TODO
    maps_info:{type:"text"},
    matress_unstaffed:{values:[true, false, null]},
    mixed_rating:{values:attrs.mixed_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"mixed_rating"},
    modifications:{type:"markdown", parent:"locales", helper:"modifications"},
    motivations:{type:"markdown", parent:"locales"},
    mtb_down_rating:{values:attrs.mtb_down_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"mtb_down_rating"},
    mtb_height_diff_portages:{type:"number", min:0, max:5000, unit:"m"},
    mtb_length_asphalt:{type:"number", min:0, max:50, unit:"km"},
    mtb_length_trail:{type:"number", min:0, max:50, unit:"km"},
    mtb_up_rating:{values:attrs.mtb_up_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"mtb_up_rating"},
    name:{disabled}, // for profile
    nb_impacted:{type:"number", min:0, max:1000, helper:"nb_impacted"},
    nb_outings:{values:attrs.nb_outings},
    nb_pages:{type:"number", min:0, max:9999, unit:"#"},
    nb_participants:{type:"number", min:0, max:1000},
    orientations:{values:attrs.orientation_types, multiple:true, queryMode:"orientations", i18n:false, helper:"orientations"},
    other_comments:{type:"markdown", parent:"locales"},
    outings:{type:"document", parent:"associations", documentType:"outing", multiple },
    paragliding_rating:{values:attrs.paragliding_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"paragliding_rating"},
    parking_fee:{values:attrs.parking_fee_types},
    partial_trip:{type:"boolean"},
    participant_count:{type:"number", min:1, max:9999},
    participants:{type:"text", helper:"participants"},
    phone:{type:"tel"},
    phone_custodian:{type:"tel"},
    place:{type:"markdown", parent:"locales"},
    previous_injuries:{values:attrs.previous_injuries},
    product_types:{values:attrs.product_types, multiple},
    prominence:{type:"number", min:0, max:9999, unit:"m"},
    public_transport:{type:"boolean"},
    public_transportation_rating:{values:attrs.public_transportation_ratings},
    public_transportation_types:{values:attrs.public_transportation_types, multiple},
    publication_date:{type:"text"},
    quality:{values:attrs.quality_types, queryMode:"valuesRangeSlider", i18n: true},
    rain_proof:{values:attrs.rain_proof_types},
    reduce_impact:{type:"markdown", parent:"locales", helper:"reduce_impact"},
    remarks:{type:"markdown", parent:"locales"},
    rescue:{type:"boolean", helper:"rescue"},
    risk:{type:"markdown", parent:"locales"},
    risk_rating:{values:attrs.risk_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"risk_rating"},
    rock_free_rating:{values:attrs.climbing_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"rock_free_rating"},
    rock_required_rating:{values:attrs.climbing_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"rock_required_rating"},
    rock_types:{values:attrs.rock_types, multiple},
    route_description:{type:"markdown", parent:"locales"},
    route_history:{type:"markdown", parent:"locales"},
    route_length:{type:"number", min:0, max:100000, unit:"m"},
    route_study:{type:"markdown", parent:"locales"},
    route_types:{values:attrs.route_types, multiple, helper:"route_types"},
    routes:{type:"document", parent:"associations", documentType:"route", multiple },
    routes_quantity:{type:"number", min:0, max:9999},
    safety:{type:"markdown", parent:"locales", helper:"safety"},
    scale:{type:"text"},
    severity:{values:attrs.severities, helper:"severity"},
    ski_exposition:{values:attrs.exposition_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"ski_exposition"},
    ski_rating:{values:attrs.ski_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"ski_rating"},
    slackline_anchor1:{type:"markdown", parent:"locales"},
    slackline_anchor2:{type:"markdown", parent:"locales"},
    slackline_height:{type:"number", min:0, unit:"m"},
    slackline_length_max:{type:"number", min:0, max:9999, unit:"m"},
    slackline_length_min:{type:"number", min:0, max:9999, unit:"m"},
    slackline_type:{values:attrs.slackline_types},
    slackline_types:{values:attrs.slackline_types, multiple}, // for waypoints
    slope:{type:'text', parent:"locales"}, //locale, but NOT markdown
    waypoint_slope:{name:"slope", type:'number', min:0, max:99, unit:"&deg;"}, //locale, but NOT markdown
    snow_clearance_rating:{values:attrs.snow_clearance_ratings},
    snow_quality:{values:attrs.condition_ratings},
    snow_quantity:{values:attrs.condition_ratings},
    snowshoe_rating:{values:attrs.snowshoe_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"snowshoe_rating"},
    summary:{type:"markdown", parent:"locales"},
    time_management:{type:"markdown", parent:"locales"},
    timing:{type:"markdown", parent:"locales"},
    title:{required, parent:"locales", minLength:3, queryMode:"input"},
    training:{type:"markdown", parent:"locales"},
    url:{type:"url", minLength:6},
    users:{type:"document", parent:"associations", documentType:"profile", multiple },
    via_ferrata_rating:{values:attrs.via_ferrata_ratings, queryMode:"valuesRangeSlider", i18n:false, helper:"via_ferrata_rating"},
    waypoint_type:{values:attrs.waypoint_types},
    waypoints:{type:"document", parent:"associations", documentType:"waypoint", multiple },
    weather:{type:"markdown", parent:"locales"},
    weather_station_types:{values:attrs.weather_station_types, multiple},
    width:{type:"number",disabled},
    xreports:{type:"document", parent:"associations", documentType:"xreport", multiple },
}
