name: Retrieve i18n from Transifex

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  retrieve-18n:
    runs-on: ubuntu-latest
    permissions:
      contents: write # the c2corg/transifex-pull-request-action pushes a branch
      pull-requests: write # ...and opens/updates a PR from it
    steps:
      - name: Checkout repository
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Retrieve i18n from Transifex and create PR if applies
        uses: c2corg/transifex-pull-request-action@b0276c82abb5b27be0ab509d8444371745b1c9ee # v5
        with:
          transifex_token: ${{ secrets.TRANSIFEX_TOKEN }}
          transifex_organisation: camptocamp-association
          transifex_project: c2corg_ui
          transifex_resource: main
          output: src/translations
          locales: ca, de, en, es, eu, fr, hu, it, ru, sl, zh_CN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: transifex/i18n
          transform: po-to-json
          labels: i18n
